//! # TPM 2.0 Model Attestation Module
//!
//! Provides a hardware security layer to attest that local GGUF models running in
//! air-gapped environments have not been tampered with or modified.
//! In production, this interfaces with `/dev/tpm0` to measure model files into PCR 12
//! and fetch an AIK signed quote.

use crate::error::{VigilError, VigilResult};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;

/// Cryptographic attestation details generated by TPM 2.0 measurements.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmAttestationReport {
    /// PCR index where the measurement is registered (PCR 12 is reserved for VIGIL models).
    pub pcr_index: u32,
    /// Calculated SHA-256 hash of the GGUF model binary.
    pub model_hash: String,
    /// Simulated TPM 2.0 quote signed by the TPM's Attestation Identity Key (AIK).
    pub tpm_signature: String,
    /// Nonce used to verify freshness and prevent replay attacks.
    pub nonce: String,
    /// Timestamp of attestation generation.
    pub timestamp: DateTime<Utc>,
    /// Whether the attestation verification succeeded.
    pub is_verified: bool,
}

/// Attest a local GGUF model path.
///
/// NOTE (Vivek): Since we're deploying in sensitive ISRO sites, we need to prove to the system
/// that the model wasn't swapped out for a backdoor version. This function reads the GGUF model
/// in chunks, hashes it, and simulates a TPM quote.
pub fn attest_gguf_model<P: AsRef<Path>>(
    model_path: P,
    nonce: &str,
) -> VigilResult<TpmAttestationReport> {
    let path = model_path.as_ref();

    // In dev mode/fallback, if the file doesn't exist, we don't crash, we return a mock report.
    let hash = if path.exists() {
        let file = File::open(path).map_err(VigilError::Io)?;
        let mut reader = BufReader::with_capacity(1024 * 1024, file);
        let mut hasher = Sha256::new();
        let mut buffer = vec![0u8; 1024 * 1024]; // 1MB heap-allocated chunk buffer

        loop {
            let count = reader.read(&mut buffer).map_err(VigilError::Io)?;
            if count == 0 {
                break;
            }
            hasher.update(&buffer[..count]);
        }
        format!("{:x}", hasher.finalize())
    } else {
        // Fallback mock hash if model file is not yet deployed
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855".to_string()
    };

    // Simulate TPM 2.0 Quote creation using AIK.
    // In a production hardware environment, this would call tpm2_quote or use the tpm2-tss library.
    let simulated_signature = format!(
        "tpm2-quote-sig:aik-key-0x81010002:pcr12-{}:nonce-{}",
        &hash[..16],
        nonce
    );

    // Verify model hash is known/safe (mocked check for the hackathon GGUF models)
    let is_verified = true;

    Ok(TpmAttestationReport {
        pcr_index: 12,
        model_hash: hash,
        tpm_signature: simulated_signature,
        nonce: nonce.to_string(),
        timestamp: Utc::now(),
        is_verified,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_mock_tpm_attestation() {
        let nonce = "test-session-nonce-12345";
        let report = attest_gguf_model(PathBuf::from("nonexistent_model.gguf"), nonce).unwrap();

        assert_eq!(report.pcr_index, 12);
        assert_eq!(report.nonce, nonce);
        assert!(report.is_verified);
        assert!(report.tpm_signature.contains("tpm2-quote-sig"));
        assert!(report.tpm_signature.contains(nonce));
    }
}
